package com.github.jacks.factoryIdle.ui

import com.github.jacks.factoryIdle.data.BuildingType
import com.github.jacks.factoryIdle.data.Resource

enum class Drawables {
    // Buttons
    BUTTON_DEFAULT_UP, BUTTON_DEFAULT_OVER, BUTTON_DEFAULT_DOWN, BUTTON_DEFAULT_DISABLED,
    BUTTON_ACCENT_UP, BUTTON_ACCENT_OVER, BUTTON_ACCENT_DOWN, BUTTON_ACCENT_DISABLED,
    BUTTON_DANGER_UP, BUTTON_DANGER_OVER, BUTTON_DANGER_DOWN, BUTTON_DANGER_DISABLED,
    BUTTON_NAVIGATION_UP, BUTTON_NAVIGATION_OVER, BUTTON_NAVIGATION_DOWN, BUTTON_NAVIGATION_SELECTED,
    // Panels
    PANEL_BG, PANEL_DARK, PANEL_INSET, TOOLTIP_BG, RESOURCE_BAR_BG,
    // Cards
    CARD_BG_RUNNING, CARD_BG_STALLED, CARD_BG_FUEL_STARVED, CARD_BG_PAUSED, CARD_BG_IDLE,
    // Progress
    PROGRESS_TRACK, PROGRESS_FILL_GREEN, PROGRESS_FILL_AMBER, PROGRESS_FILL_BLUE, PROGRESS_FILL_RED,
    // Pixels
    PX_DIVIDER, PX_WHITE, PX_BLACK,
    // Status dots
    STATUS_RUNNING, STATUS_STALLED, STATUS_FUEL_STARVED, STATUS_PAUSED, STATUS_IDLE,
    // Navigation icons
    ICON_NAVIGATION_FACTORY, ICON_NAVIGATION_POWER, ICON_NAVIGATION_RESEARCH, ICON_NAVIGATION_PROGRESS, ICON_NAVIGATION_SETTINGS,
    ICON_NAVIGATION_MINING, ICON_NAVIGATION_CRAFT,
    // Raw resource icons (small = 32px, medium = 64px, large = 128px)
    ICON_RESOURCE_IRON_ORE_SMALL, ICON_RESOURCE_IRON_ORE_MEDIUM, ICON_RESOURCE_IRON_ORE_LARGE,
    ICON_RESOURCE_COAL_SMALL, ICON_RESOURCE_COAL_MEDIUM, ICON_RESOURCE_COAL_LARGE,
    ICON_RESOURCE_STONE_SMALL, ICON_RESOURCE_STONE_MEDIUM, ICON_RESOURCE_STONE_LARGE,
    ICON_RESOURCE_COPPER_ORE_SMALL, ICON_RESOURCE_COPPER_ORE_MEDIUM, ICON_RESOURCE_COPPER_ORE_LARGE,
    // Processed material icons
    ICON_PROCESSED_IRON_PLATE_SMALL, ICON_PROCESSED_IRON_PLATE_MEDIUM, ICON_PROCESSED_IRON_PLATE_LARGE,
    ICON_PROCESSED_COPPER_PLATE_SMALL, ICON_PROCESSED_COPPER_PLATE_MEDIUM, ICON_PROCESSED_COPPER_PLATE_LARGE,
    // Component icons
    ICON_COMPONENT_COPPER_WIRE_SMALL, ICON_COMPONENT_COPPER_WIRE_MEDIUM, ICON_COMPONENT_COPPER_WIRE_LARGE,
    ICON_COMPONENT_IRON_GEAR_SMALL, ICON_COMPONENT_IRON_GEAR_MEDIUM, ICON_COMPONENT_IRON_GEAR_LARGE,
    // Science pack icons
    ICON_SCIENCE_RED_SMALL, ICON_SCIENCE_RED_MEDIUM, ICON_SCIENCE_RED_LARGE,
    ICON_SCIENCE_ORANGE_SMALL, ICON_SCIENCE_ORANGE_MEDIUM, ICON_SCIENCE_ORANGE_LARGE,
    ICON_SCIENCE_YELLOW_SMALL, ICON_SCIENCE_YELLOW_MEDIUM, ICON_SCIENCE_YELLOW_LARGE,
    ICON_SCIENCE_GREEN_SMALL, ICON_SCIENCE_GREEN_MEDIUM, ICON_SCIENCE_GREEN_LARGE,
    ICON_SCIENCE_BLUE_SMALL, ICON_SCIENCE_BLUE_MEDIUM, ICON_SCIENCE_BLUE_LARGE,
    ICON_SCIENCE_PURPLE_SMALL, ICON_SCIENCE_PURPLE_MEDIUM, ICON_SCIENCE_PURPLE_LARGE,
    // Building icons (small = 32px, medium = 64px, large = 128px)
    ICON_BUILDING_STONE_FURNACE_SMALL, ICON_BUILDING_STONE_FURNACE_MEDIUM, ICON_BUILDING_STONE_FURNACE_LARGE,
    ICON_BUILDING_BASIC_MINER_SMALL, ICON_BUILDING_BASIC_MINER_MEDIUM, ICON_BUILDING_BASIC_MINER_LARGE,
    ICON_BUILDING_ASSEMBLER_MK1_SMALL, ICON_BUILDING_ASSEMBLER_MK1_MEDIUM, ICON_BUILDING_ASSEMBLER_MK1_LARGE,
    ICON_BUILDING_RESEARCH_FACILITY_SMALL, ICON_BUILDING_RESEARCH_FACILITY_MEDIUM, ICON_BUILDING_RESEARCH_FACILITY_LARGE,
    ICON_BUILDING_MINER_MK1_SMALL, ICON_BUILDING_MINER_MK1_MEDIUM, ICON_BUILDING_MINER_MK1_LARGE;

    operator fun invoke() = name.lowercase()
}

fun Resource.smallIconKey(): String = when (this) {
    Resource.IRON_ORE       -> Drawables.ICON_RESOURCE_IRON_ORE_SMALL()
    Resource.COAL           -> Drawables.ICON_RESOURCE_COAL_SMALL()
    Resource.STONE          -> Drawables.ICON_RESOURCE_STONE_SMALL()
    Resource.COPPER_ORE     -> Drawables.ICON_RESOURCE_COPPER_ORE_SMALL()
    Resource.IRON_PLATE     -> Drawables.ICON_PROCESSED_IRON_PLATE_SMALL()
    Resource.COPPER_PLATE   -> Drawables.ICON_PROCESSED_COPPER_PLATE_SMALL()
    Resource.COPPER_WIRE    -> Drawables.ICON_COMPONENT_COPPER_WIRE_SMALL()
    Resource.IRON_GEAR      -> Drawables.ICON_COMPONENT_IRON_GEAR_SMALL()
    Resource.RED_SCIENCE    -> Drawables.ICON_SCIENCE_RED_SMALL()
    Resource.ORANGE_SCIENCE -> Drawables.ICON_SCIENCE_ORANGE_SMALL()
    Resource.YELLOW_SCIENCE -> Drawables.ICON_SCIENCE_YELLOW_SMALL()
    Resource.GREEN_SCIENCE  -> Drawables.ICON_SCIENCE_GREEN_SMALL()
    Resource.BLUE_SCIENCE   -> Drawables.ICON_SCIENCE_BLUE_SMALL()
    Resource.PURPLE_SCIENCE -> Drawables.ICON_SCIENCE_PURPLE_SMALL()
}

fun Resource.mediumIconKey(): String = when (this) {
    Resource.IRON_ORE       -> Drawables.ICON_RESOURCE_IRON_ORE_MEDIUM()
    Resource.COAL           -> Drawables.ICON_RESOURCE_COAL_MEDIUM()
    Resource.STONE          -> Drawables.ICON_RESOURCE_STONE_MEDIUM()
    Resource.COPPER_ORE     -> Drawables.ICON_RESOURCE_COPPER_ORE_MEDIUM()
    Resource.IRON_PLATE     -> Drawables.ICON_PROCESSED_IRON_PLATE_MEDIUM()
    Resource.COPPER_PLATE   -> Drawables.ICON_PROCESSED_COPPER_PLATE_MEDIUM()
    Resource.COPPER_WIRE    -> Drawables.ICON_COMPONENT_COPPER_WIRE_MEDIUM()
    Resource.IRON_GEAR      -> Drawables.ICON_COMPONENT_IRON_GEAR_MEDIUM()
    Resource.RED_SCIENCE    -> Drawables.ICON_SCIENCE_RED_MEDIUM()
    Resource.ORANGE_SCIENCE -> Drawables.ICON_SCIENCE_ORANGE_MEDIUM()
    Resource.YELLOW_SCIENCE -> Drawables.ICON_SCIENCE_YELLOW_MEDIUM()
    Resource.GREEN_SCIENCE  -> Drawables.ICON_SCIENCE_GREEN_MEDIUM()
    Resource.BLUE_SCIENCE   -> Drawables.ICON_SCIENCE_BLUE_MEDIUM()
    Resource.PURPLE_SCIENCE -> Drawables.ICON_SCIENCE_PURPLE_MEDIUM()
}

fun Resource.largeIconKey(): String = when (this) {
    Resource.IRON_ORE       -> Drawables.ICON_RESOURCE_IRON_ORE_LARGE()
    Resource.COAL           -> Drawables.ICON_RESOURCE_COAL_LARGE()
    Resource.STONE          -> Drawables.ICON_RESOURCE_STONE_LARGE()
    Resource.COPPER_ORE     -> Drawables.ICON_RESOURCE_COPPER_ORE_LARGE()
    Resource.IRON_PLATE     -> Drawables.ICON_PROCESSED_IRON_PLATE_LARGE()
    Resource.COPPER_PLATE   -> Drawables.ICON_PROCESSED_COPPER_PLATE_LARGE()
    Resource.COPPER_WIRE    -> Drawables.ICON_COMPONENT_COPPER_WIRE_LARGE()
    Resource.IRON_GEAR      -> Drawables.ICON_COMPONENT_IRON_GEAR_LARGE()
    Resource.RED_SCIENCE    -> Drawables.ICON_SCIENCE_RED_LARGE()
    Resource.ORANGE_SCIENCE -> Drawables.ICON_SCIENCE_ORANGE_LARGE()
    Resource.YELLOW_SCIENCE -> Drawables.ICON_SCIENCE_YELLOW_LARGE()
    Resource.GREEN_SCIENCE  -> Drawables.ICON_SCIENCE_GREEN_LARGE()
    Resource.BLUE_SCIENCE   -> Drawables.ICON_SCIENCE_BLUE_LARGE()
    Resource.PURPLE_SCIENCE -> Drawables.ICON_SCIENCE_PURPLE_LARGE()
}

fun BuildingType.smallIconKey(): String = when (this) {
    BuildingType.STONE_FURNACE     -> Drawables.ICON_BUILDING_STONE_FURNACE_SMALL()
    BuildingType.BASIC_MINER       -> Drawables.ICON_BUILDING_BASIC_MINER_SMALL()
    BuildingType.ASSEMBLER_MK1     -> Drawables.ICON_BUILDING_ASSEMBLER_MK1_SMALL()
    BuildingType.RESEARCH_FACILITY -> Drawables.ICON_BUILDING_RESEARCH_FACILITY_SMALL()
    BuildingType.MINER_MK1         -> Drawables.ICON_BUILDING_MINER_MK1_SMALL()
}

fun BuildingType.mediumIconKey(): String = when (this) {
    BuildingType.STONE_FURNACE     -> Drawables.ICON_BUILDING_STONE_FURNACE_MEDIUM()
    BuildingType.BASIC_MINER       -> Drawables.ICON_BUILDING_BASIC_MINER_MEDIUM()
    BuildingType.ASSEMBLER_MK1     -> Drawables.ICON_BUILDING_ASSEMBLER_MK1_MEDIUM()
    BuildingType.RESEARCH_FACILITY -> Drawables.ICON_BUILDING_RESEARCH_FACILITY_MEDIUM()
    BuildingType.MINER_MK1         -> Drawables.ICON_BUILDING_MINER_MK1_MEDIUM()
}

fun BuildingType.largeIconKey(): String = when (this) {
    BuildingType.STONE_FURNACE     -> Drawables.ICON_BUILDING_STONE_FURNACE_LARGE()
    BuildingType.BASIC_MINER       -> Drawables.ICON_BUILDING_BASIC_MINER_LARGE()
    BuildingType.ASSEMBLER_MK1     -> Drawables.ICON_BUILDING_ASSEMBLER_MK1_LARGE()
    BuildingType.RESEARCH_FACILITY -> Drawables.ICON_BUILDING_RESEARCH_FACILITY_LARGE()
    BuildingType.MINER_MK1         -> Drawables.ICON_BUILDING_MINER_MK1_LARGE()
}
