package com.github.jacks.factoryIdle.ui

import com.github.jacks.factoryIdle.data.BuildingType
import com.github.jacks.factoryIdle.data.Resource

enum class Drawables {
    // Buttons
    BUTTON_DEFAULT_UP, BUTTON_DEFAULT_OVER, BUTTON_DEFAULT_DOWN, BUTTON_DEFAULT_DISABLED,
    BUTTON_ACCENT_UP, BUTTON_ACCENT_OVER, BUTTON_ACCENT_DOWN, BUTTON_ACCENT_DISABLED,
    BUTTON_DANGER_UP, BUTTON_DANGER_OVER, BUTTON_DANGER_DOWN, BUTTON_DANGER_DISABLED,
    BUTTON_NAVIGATION_UP, BUTTON_NAVIGATION_OVER, BUTTON_NAVIGATION_DOWN, BUTTON_NAVIGATION_SELECTED,
    // Panels
    PANEL_BG, PANEL_DARK, PANEL_INSET, TOOLTIP_BG, RESOURCE_BAR_BG,
    // Cards
    CARD_BG_RUNNING, CARD_BG_STALLED, CARD_BG_FUEL_STARVED, CARD_BG_PAUSED, CARD_BG_IDLE,
    // Progress
    PROGRESS_TRACK, PROGRESS_FILL_GREEN, PROGRESS_FILL_AMBER, PROGRESS_FILL_BLUE, PROGRESS_FILL_RED,
    // Pixels
    PX_DIVIDER, PX_WHITE, PX_BLACK,
    // Status dots
    STATUS_RUNNING, STATUS_STALLED, STATUS_FUEL_STARVED, STATUS_PAUSED, STATUS_IDLE,
    // Navigation icons
    ICON_NAVIGATION_FACTORY, ICON_NAVIGATION_POWER, ICON_NAVIGATION_RESEARCH, ICON_NAVIGATION_PROGRESS, ICON_NAVIGATION_SETTINGS,
    // Raw resource icons (small = 32px, medium = 64px, large = 128px)
    ICON_RESOURCE_IRON_ORE_SMALL, ICON_RESOURCE_IRON_ORE_MEDIUM, ICON_RESOURCE_IRON_ORE_LARGE,
    ICON_RESOURCE_COAL_SMALL, ICON_RESOURCE_COAL_MEDIUM, ICON_RESOURCE_COAL_LARGE,
    ICON_RESOURCE_STONE_SMALL, ICON_RESOURCE_STONE_MEDIUM, ICON_RESOURCE_STONE_LARGE,
    ICON_RESOURCE_COPPER_ORE_SMALL, ICON_RESOURCE_COPPER_ORE_MEDIUM, ICON_RESOURCE_COPPER_ORE_LARGE,
    // Processed material icons (small = 32px, medium = 64px, large = 128px)
    ICON_PROCESSED_IRON_PLATE_SMALL, ICON_PROCESSED_IRON_PLATE_MEDIUM, ICON_PROCESSED_IRON_PLATE_LARGE,
    ICON_PROCESSED_COPPER_PLATE_SMALL, ICON_PROCESSED_COPPER_PLATE_MEDIUM, ICON_PROCESSED_COPPER_PLATE_LARGE,
    // Building icons (small = 32px, medium = 64px, large = 128px)
    ICON_BUILDING_STONE_FURNACE_SMALL, ICON_BUILDING_STONE_FURNACE_MEDIUM, ICON_BUILDING_STONE_FURNACE_LARGE,
    ICON_BUILDING_BASIC_MINER_SMALL, ICON_BUILDING_BASIC_MINER_MEDIUM, ICON_BUILDING_BASIC_MINER_LARGE;

    operator fun invoke() = name.lowercase()
}

fun Resource.smallIconKey(): String = when (this) {
    Resource.IRON_ORE     -> Drawables.ICON_RESOURCE_IRON_ORE_SMALL()
    Resource.COAL         -> Drawables.ICON_RESOURCE_COAL_SMALL()
    Resource.STONE        -> Drawables.ICON_RESOURCE_STONE_SMALL()
    Resource.COPPER_ORE   -> Drawables.ICON_RESOURCE_COPPER_ORE_SMALL()
    Resource.IRON_PLATE   -> Drawables.ICON_PROCESSED_IRON_PLATE_SMALL()
    Resource.COPPER_PLATE -> Drawables.ICON_PROCESSED_COPPER_PLATE_SMALL()
}

fun Resource.mediumIconKey(): String = when (this) {
    Resource.IRON_ORE     -> Drawables.ICON_RESOURCE_IRON_ORE_MEDIUM()
    Resource.COAL         -> Drawables.ICON_RESOURCE_COAL_MEDIUM()
    Resource.STONE        -> Drawables.ICON_RESOURCE_STONE_MEDIUM()
    Resource.COPPER_ORE   -> Drawables.ICON_RESOURCE_COPPER_ORE_MEDIUM()
    Resource.IRON_PLATE   -> Drawables.ICON_PROCESSED_IRON_PLATE_MEDIUM()
    Resource.COPPER_PLATE -> Drawables.ICON_PROCESSED_COPPER_PLATE_MEDIUM()
}

fun Resource.largeIconKey(): String = when (this) {
    Resource.IRON_ORE     -> Drawables.ICON_RESOURCE_IRON_ORE_LARGE()
    Resource.COAL         -> Drawables.ICON_RESOURCE_COAL_LARGE()
    Resource.STONE        -> Drawables.ICON_RESOURCE_STONE_LARGE()
    Resource.COPPER_ORE   -> Drawables.ICON_RESOURCE_COPPER_ORE_LARGE()
    Resource.IRON_PLATE   -> Drawables.ICON_PROCESSED_IRON_PLATE_LARGE()
    Resource.COPPER_PLATE -> Drawables.ICON_PROCESSED_COPPER_PLATE_LARGE()
}

fun BuildingType.smallIconKey(): String = when (this) {
    BuildingType.STONE_FURNACE -> Drawables.ICON_BUILDING_STONE_FURNACE_SMALL()
    BuildingType.BASIC_MINER   -> Drawables.ICON_BUILDING_BASIC_MINER_SMALL()
}

fun BuildingType.mediumIconKey(): String = when (this) {
    BuildingType.STONE_FURNACE -> Drawables.ICON_BUILDING_STONE_FURNACE_MEDIUM()
    BuildingType.BASIC_MINER   -> Drawables.ICON_BUILDING_BASIC_MINER_MEDIUM()
}

fun BuildingType.largeIconKey(): String = when (this) {
    BuildingType.STONE_FURNACE -> Drawables.ICON_BUILDING_STONE_FURNACE_LARGE()
    BuildingType.BASIC_MINER   -> Drawables.ICON_BUILDING_BASIC_MINER_LARGE()
}
