package com.github.jacks.factoryIdle.ui

enum class Drawables {
    // Buttons
    BUTTON_DEFAULT_UP, BUTTON_DEFAULT_OVER, BUTTON_DEFAULT_DOWN, BUTTON_DEFAULT_DISABLED,
    BUTTON_ACCENT_UP, BUTTON_ACCENT_OVER, BUTTON_ACCENT_DOWN, BUTTON_ACCENT_DISABLED,
    BUTTON_DANGER_UP, BUTTON_DANGER_OVER, BUTTON_DANGER_DOWN, BUTTON_DANGER_DISABLED,
    BUTTON_NAVIGATION_UP, BUTTON_NAVIGATION_OVER, BUTTON_NAVIGATION_DOWN, BUTTON_NAVIGATION_SELECTED,
    // Panels
    PANEL_BG, PANEL_DARK, PANEL_INSET, TOOLTIP_BG, RESOURCE_BAR_BG,
    // Cards
    CARD_BG_RUNNING, CARD_BG_STALLED, CARD_BG_FUEL_STARVED, CARD_BG_PAUSED, CARD_BG_IDLE,
    // Progress
    PROGRESS_TRACK, PROGRESS_FILL_GREEN, PROGRESS_FILL_AMBER, PROGRESS_FILL_BLUE, PROGRESS_FILL_RED,
    // Pixels
    PX_DIVIDER, PX_WHITE, PX_BLACK,
    // Status dots
    STATUS_RUNNING, STATUS_STALLED, STATUS_FUEL_STARVED, STATUS_PAUSED, STATUS_IDLE,
    // Navigation icons
    ICON_NAVIGATION_FACTORY, ICON_NAVIGATION_POWER, ICON_NAVIGATION_RESEARCH, ICON_NAVIGATION_PROGRESS, ICON_NAVIGATION_SETTINGS,
    // Resource icons (sm = 20px, md = 36px)
    ICON_RSC_IRON_ORE_SM, ICON_RSC_IRON_ORE_MD,
    ICON_RSC_COAL_SM, ICON_RSC_COAL_MD,
    ICON_RSC_STONE_SM, ICON_RSC_STONE_MD,
    ICON_RSC_IRON_PLATE_SM, ICON_RSC_IRON_PLATE_MD,
    // Building icons and art
    ICON_BLD_STONE_FURNACE, ICON_BLD_BASIC_MINER,
    BLD_ART_STONE_FURNACE, BLD_ART_BASIC_MINER;

    operator fun invoke() = name.lowercase()
}
